# Generated by Django 2.2.4 on 2019-10-20 06:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='description',
            field=ckeditor.fields.RichTextField(default=0),
        ),
    ]
